server:
  port: 10373

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

zuul:
  routes:
    api-hi:
      path: /api-hi/**
      serviceId: consumer-hi